#!/bin/zsh
# Build one KeY checkout into a runnable benchmark config and register it.
#
#   build_config.sh <name> <path-to-key-checkout> [workers]
#
# Steps: apply the Java-model phase timer to ProblemInitializer, copy BenchMain into the checkout's
# key.core.example module, run installDist (which assembles every runtime jar into one lib dir),
# then add or replace this version's row in the registry. Called once per version by `keyovertime`.
#
# Every version is built with the same JDK that will run the measurements. A build/run split across
# two JDKs, or across two architectures, would put a difference into the numbers that has nothing to
# do with KeY.
#
# Environment:
#   BENCH_JAVA_HOME    JDK for the build (required; the entry point detects it)
#   BENCH_CONFIGS      registry CSV to write the row into (required)
#   BENCH_JAVA_TIMER   on|off. "off" leaves ProblemInitializer untouched, so the checkout is built
#                      unmodified apart from the added BenchMain; the Java-model metric is then
#                      unavailable for this version and reports javaMs=-1.
#   BENCH_GRADLE_JOBS  --max-workers for Gradle; empty lets Gradle decide
#   KEYOVERTIME_HOME   this project's root (default: the parent of this script)
set -eu
if [[ $# -lt 2 || $# -gt 3 ]]; then
    print -ru2 -- "usage: build_config.sh <name> <path-to-key-checkout> [workers]"
    exit 1
fi
NAME=$1
WT=$2
# Worker count this row is measured at, empty for the run's default. A row that names one is a
# parallel-only row: it exists to add one more worker count to the comparison, so measuring it
# single-threaded as well would only produce a second identical sc column.
WORKERS=${3:-}
HOME_DIR=${KEYOVERTIME_HOME:-${0:A:h:h}}
BENCH_JAVA_TIMER=${BENCH_JAVA_TIMER:-on}
BENCH_GRADLE_JOBS=${BENCH_GRADLE_JOBS:-}
CFG=${BENCH_CONFIGS:?BENCH_CONFIGS is not set}

die() { print -ru2 -- "build_config: $*"; exit 1 }

[[ -x ${BENCH_JAVA_HOME:-}/bin/java ]] || die "no java at ${BENCH_JAVA_HOME:-<unset>}/bin/java"
[[ -d $WT/key.core.example ]] || die "$WT/key.core.example not found (not a KeY checkout?)"

if [[ $BENCH_JAVA_TIMER == on ]]; then
    python3 $HOME_DIR/python/patch_readjava.py $WT
else
    print -r -- "BENCH_JAVA_TIMER=off: leaving ProblemInitializer unpatched (javaMs unavailable)"
fi

EXDIR=$WT/key.core.example/src/main/java/org/key_project
mkdir -p $EXDIR
cp $HOME_DIR/java/BenchMain.java $EXDIR/BenchMain.java

print -r -- "building :key.core.example:installDist in $WT"
typeset -a GRADLE_JOBS
[[ -n $BENCH_GRADLE_JOBS ]] && GRADLE_JOBS=(--max-workers $BENCH_GRADLE_JOBS)
( cd $WT && JAVA_HOME=$BENCH_JAVA_HOME ./gradlew :key.core.example:installDist \
    --console=plain $GRADLE_JOBS )

LIB=$WT/key.core.example/build/install/key.core.example/lib
[[ -d $LIB ]] || die "installDist lib dir not found at $LIB"

EXAMPLES=$WT/key.ui/examples
[[ -d $EXAMPLES ]] || die "examples tree not found at $EXAMPLES"

# Directory the standard taclet files are read from, handed to KeY as
# -Dorg.key_project.stdTacletDirectory. KeY 2.12.4 cannot follow the \include chain when the rule
# files sit inside a jar: it resolves each include against the parent of the previous rule file, and
# that parent comes back as a plain path once the zip filesystem is left behind, so ldt.key is
# looked up at the filesystem root and the load dies. Pointing every version at its own unpacked
# build resources sidesteps that, and does so identically for all of them, so the taclet base is
# read the same way everywhere rather than from a jar on some versions and a directory on others.
RULES=$WT/key.core/build/resources/main/de/uka/ilkd/key/proof/rules
[[ -f $RULES/standardRules.key ]] || die "standardRules.key not found under $RULES"

# Does this version have the goal-parallel prover? Versions before the multithreading merge do not
# know key.prover.parallel at all, and running them under "mt" would silently produce a second
# single-threaded number rather than a parallel one. Detected from the source, so a newly added
# version classifies itself.
if grep -rqs "key.prover.parallel" $WT/key.core/src/main/java; then
    MT=1
else
    MT=0
fi

# Generated, so it carries a line saying so; the data rows below it are written by csvio, which
# quotes a path containing a comma the way the readers expect.
if [[ ! -f $CFG ]]; then
    print -r -- "# Generated by keyovertime. One row per built checkout; do not edit." > $CFG
    print -r -- "name,libdir,examplesdir,rulesdir,mt,workers" >> $CFG
fi
python3 $HOME_DIR/python/csvio.py upsert $CFG --key "$NAME" \
    --row "$NAME" "$LIB" "$EXAMPLES" "$RULES" "$MT" "$WORKERS"
print -r -- "registered $NAME (parallel prover: $([[ $MT == 1 ]] && print -- yes || print -- no))"
